# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CSIT 101
subtitle: 'Computer Science and Information Technology Study Resources'
description: ' CSIT 101 is a platform for Computer Science and Information Technology students. It provides study resources, tutorials, exam preparation materials, and more.'
keywords: 'CSIT, Computer Science, Digital Logic, Programming, Notes, Study, Nepal, Patan Campus, Tribhuvan University, TU, BIT, Study Resources, Tutorials, Exam Preparation, Syllabus, 101, First Semester, Second Semester, Past Questions, University Notes, Materials, Basics, Advanced, Practical, Exam Solutions, Study Guides, Practice Papers, Lecture Notes, Solution Guides, Question Banks, CSIT Notes, BIT Notes, University Handouts, Study Guides, Preparation Tips, Digital Logic Notes, Programming Tutorials, Practical Materials, Syllabus PDF, Learning Resources, Tuition Materials, Study Tutorials, CSIT Exam Papers, Programming Notes TU, Digital Logic Resources TU, CSIT Learning Resources TU, Past Papers TU, BIT Preparation Guide, TU Study Resources, Exam Preparation TU, TU University Notes, Study Handouts, CSIT Learning Guides, BIT Syllabus, Practical Solutions, Semester-wise Resources, TU Handouts, TU CSIT Notes, CSIT Notes Nepal, BIT Notes Nepal, Digital Logic Resources Nepal, CSIT Resources TU, TU Exam Preparation, CSIT Notes TU Patan Campus, TU Notes Nepal, Programming Notes TU Patan Campus, TU BIT Notes Patan Campus, BIT Notes TU Patan Campus, Exam Tips TU Patan Campus, TU Study Resources Patan Campus, TU Notes Patan Campus, CSIT Exam Preparation Patan Campus, TU Past Papers Patan Campus, CSIT Study Guides TU, BIT Syllabus TU, Practical Solutions TU, Study Materials TU, TU University Notes Patan Campus, Exam Solutions TU Patan Campus, TU Study Guides Patan Campus, CSIT Past Questions TU, CSIT Preparation Guide TU, TU Exam Resources Patan Campus, BIT Preparation Guide TU Patan Campus, TU Practical Materials Patan Campus, Digital Logic Solutions TU, TU Programming Notes Patan Campus, Exam Questions TU Patan Campus, TU Study Tutorials Patan Campus, TU CSIT Practice Papers, CSIT Resources TU Patan Campus, TU Digital Logic Notes Patan Campus, BIT Exam Solutions TU, TU Study Materials Patan Campus, TU Exam Preparation Guides Patan Campus, TU Programming Resources Patan Campus, CSIT Question Bank TU Patan Campus, TU Solutions Patan Campus, TU Study Papers Patan Campus, TU Past Exam Papers Patan Campus, TU Learning Resources Patan Campus, TU BIT Practice Papers Patan Campus, TU Exam Preparation Materials Patan Campus, TU Study Solutions Patan Campus, TU Digital Logic Exam Papers Patan Campus, TU Programming Practice Papers Patan Campus, TU CSIT Handouts Patan Campus, TU BIT Question Papers Patan Campus, TU Learning Guides Patan Campus, TU Study Handouts Patan Campus, TU Exam Resources TU, TU Exam Guides Patan Campus, TU Practical Notes Patan Campus, TU Solutions Notes Patan Campus, TU Practice Resources Patan Campus, TU Study Guides TU Patan Campus, TU Exam Tutorials Patan Campus, TU Past Resources Patan Campus, TU Study Questions Patan Campus, TU Learning Materials Patan Campus, TU BIT Exam Prep Materials Patan Campus, TU Past Practice Papers Patan Campus, TU Programming Solutions Patan Campus, TU Study Exam Solutions Patan Campus, TU Programming Handouts Patan Campus, TU Practical Exam Papers Patan Campus, TU Exam Study Guides Patan Campus, TU BIT Study Tutorials Patan Campus, TU CSIT Study Solutions Patan Campus, TU Exam Preparation Guides Patan Campus, TU Past Tutorials Patan Campus, TU BIT Practice Papers Patan Campus, TU Programming Study Notes Patan Campus, TU Solutions Handouts Patan Campus, TU Study Exam Questions Patan Campus, TU Exam Prep Solutions Patan Campus, TU Practical Solutions Patan Campus, TU BIT Exam Questions Patan Campus, TU Study Handouts TU Patan Campus, TU Exam Materials Patan Campus, TU Study Resources Patan Campus, TU Programming Practice Solutions Patan Campus, TU Study Solutions Patan Campus, TU Exam Questions Patan Campus, TU Programming Handouts Patan Campus, TU Study Exam Solutions Patan Campus, TU Practical Study Notes Patan Campus, TU Exam Prep Tutorials Patan Campus, TU Programming Exam Prep Notes Patan Campus, TU Exam Guides Patan Campus, TU Study Questions Patan Campus, TU Practical Exam Notes Patan Campus, TU Exam Solutions Patan Campus, TU BIT Exam Preparation Patan Campus, TU Practical Tutorials Patan Campus, TU Study Tutorials Patan Campus, TU Exam Prep Guides Patan Campus, TU Study Prep Materials Patan Campus, TU Exam Handouts Patan Campus, TU Programming Study Questions Patan Campus, TU Study Prep Papers Patan Campus, TU Exam Preparation Guides Patan Campus, TU Study Practice Guides Patan Campus, TU Exam Questions Patan Campus, TU Exam Papers Patan Campus, TU Programming Study Tutorials Patan Campus, TU Study Exam Prep Notes Patan Campus, TU Exam Preparation Papers Patan Campus, TU Practical Study Papers Patan Campus, TU Exam Preparation Notes Patan Campus, TU Study Exam Guides Patan Campus, TU Exam Guides Patan Campus, TU Programming Practice Tutorials Patan Campus, TU Study Practice Solutions Patan Campus, TU Exam Preparation Papers Patan Campus, TU Study Practice Papers Patan Campus, TU Exam Practice Solutions Patan Campus, TU Exam Papers Patan Campus, TU Study Preparation Papers Patan Campus, TU Study Practice Questions Patan Campus, TU Exam Preparation Practice Notes Patan Campus, TU Study Preparation Notes Patan Campus, TU Programming Practice Questions Patan Campus, TU Study Practice Notes Patan Campus, TU Exam Preparation Prep Notes Patan Campus, TU Study Practice Preparation Papers Patan Campus, TU Study Practice Prep Notes Patan Campus, TU Programming Practice Questions Patan Campus, TU Study Preparation Solutions Patan Campus, TU Exam Preparation Practice Papers Patan Campus, TU Study Practice Prep Papers Patan Campus, TU Programming Practice Preparation Papers Patan Campus, TU Study Practice Practice Papers Patan Campus, TU Study Preparation Practice Papers Patan Campus, TU Study Practice Exam Papers Patan Campus, TU Study Preparation Practice Papers Patan Campus, TU Exam Preparation Prep Notes Patan Campus, TU Programming Practice Practice Papers Patan Campus, TU Study Preparation Practice Notes Patan Campus, TU Study Practice Practice Notes Patan Campus, TU Programming Practice Practice Notes Patan Campus, TU Programming Practice Preparation Notes Patan Campus, TU Study Preparation Practice Practice Papers Patan Campus, TU Study Preparation Practice Preparation Notes Patan Campus, TU Study Practice Preparation Papers Patan Campus, TU Study Preparation Practice Preparation Papers Patan Campus, TU Study Preparation Practice Preparation Practice Notes Patan Campus, TU Study Practice Preparation Preparation Papers Patan Campus
'
author: Llyr4472
language: en
timezone: 'Asia/Kathmandu'


# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://csit101.netlify.app/
permalink: :category/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/Llyr4472/blog
  branch: production

# minifier
all_minifier: true

html_minifier:
  enable: true
  ignore_error: false
  exclude:

css_minifier:
  enable: true
  exclude:
    - "*.min.css"

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - "*.min.js"

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  exclude:
    - "jpg"
    - "webp"

sitemap:
  path: sitemap.xml



search:
  path: search.json
  field: post
  content: true
  format: striptags